modLoader="javafml"
loaderVersion="36.2.0"
license="All Rights Reserved"

[[mods]]
modId="flansmodultimate_wolffstarwars"
version="${module_version}"
displayName="Flan's Mod Ultimate 2: Wolff's Star Wars Pack"
logoFile="wolffstarwars.png"
authors="Wolff"
displayTest = "NONE"
description=''''''

[[dependencies.flansmodultimate_wolffstarwars]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansmodultimate_wolffstarwars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansmodultimate_wolffstarwars]]
    modId="flansmodultimate"
    mandatory=true
    versionRange="*"
    ordering="BEFORE"
    side="BOTH"
