modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="flansmodultimate_wolffstarwars"
version="3.0"
displayName="Wolff's Star Wars Pack"
authors="Wolff"
logoFile="wolffstarwars.png"
description=''''''

[[dependencies.flansmodultimate_wolffstarwars]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolffstarwars]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolffstarwars]]
modId="flansmodultimate"
type="required"
versionRange="*"
ordering="BEFORE"
side="BOTH"
