modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="flansmodultimate_wolff_starwars"
version="3.0"
displayName="Wolff's Star Wars Content for Flan's Mod Ultimate 2"
authors="Wolff"
description=''''''

[[dependencies.flansmodultimate_wolff_starwars]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolff_starwars]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolff_starwars]]
modId="flansmodultimate"
type="required"
versionRange="[2.0-beta-5,)"
ordering="BEFORE"
side="BOTH"
